# Generated by Django 5.1 on 2025-09-14 16:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Takvim Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Renk Kodu')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan Takvim')),
                ('is_public', models.BooleanField(default=False, verbose_name='Herkese Açık')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Takvim',
                'verbose_name_plural': 'Takvimler',
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('start_datetime', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('end_datetime', models.DateTimeField(verbose_name='Bitiş Tarihi')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='Tüm Gün')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Tekrarlayan')),
                ('recurrence_pattern', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tekrarlama Deseni')),
                ('recurrence_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Tekrarlama Bitiş Tarihi')),
                ('event_type', models.CharField(choices=[('meeting', 'Toplantı'), ('appointment', 'Randevu'), ('task', 'Görev'), ('reminder', 'Hatırlatıcı'), ('holiday', 'Tatil'), ('personal', 'Kişisel'), ('work', 'İş'), ('other', 'Diğer')], default='other', max_length=20, verbose_name='Etkinlik Türü')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Konum')),
                ('is_important', models.BooleanField(default=False, verbose_name='Önemli')),
                ('is_private', models.BooleanField(default=False, verbose_name='Özel')),
                ('reminder_minutes', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10080)], verbose_name='Hatırlatma Süresi (Dakika)')),
                ('send_notification', models.BooleanField(default=True, verbose_name='Bildirim Gönder')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calendar_app.calendar', verbose_name='Takvim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Etkinlik',
                'verbose_name_plural': 'Etkinlikler',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='event_attachments/', verbose_name='Dosya')),
                ('filename', models.CharField(max_length=255, verbose_name='Dosya Adı')),
                ('file_size', models.PositiveIntegerField(verbose_name='Dosya Boyutu')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme Tarihi')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='calendar_app.event', verbose_name='Etkinlik')),
            ],
            options={
                'verbose_name': 'Etkinlik Eki',
                'verbose_name_plural': 'Etkinlik Ekleri',
            },
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_datetime', models.DateTimeField(verbose_name='Hatırlatma Tarihi')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Gönderildi')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gönderilme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='calendar_app.event', verbose_name='Etkinlik')),
            ],
            options={
                'verbose_name': 'Etkinlik Hatırlatıcısı',
                'verbose_name_plural': 'Etkinlik Hatırlatıcıları',
                'ordering': ['reminder_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_organizer', models.BooleanField(default=False, verbose_name='Organizatör')),
                ('response_status', models.CharField(choices=[('pending', 'Beklemede'), ('accepted', 'Kabul Edildi'), ('declined', 'Reddedildi'), ('tentative', 'Belirsiz')], default='pending', max_length=20, verbose_name='Yanıt Durumu')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Katılım Tarihi')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='calendar_app.event', verbose_name='Etkinlik')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Etkinlik Katılımcısı',
                'verbose_name_plural': 'Etkinlik Katılımcıları',
                'unique_together': {('event', 'user')},
            },
        ),
    ]
