# Generated by Django 5.1 on 2025-09-14 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='start_datetime',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='end_datetime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='eventreminder',
            old_name='reminder_datetime',
            new_name='reminder_time',
        ),
    ]
