# Generated by Django 5.1 on 2025-09-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_auto_20250914_2204'),
    ]

    operations = [
    ]
